name: Deploy Frontend

on:
  push:
    branches:
      - main
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t <<IMAGE_NAME>> -f ./frontend/Dockerfile.dev ./frontend
      - run: docker run -e CI=true <<IMAGE_NAME>> npm test
  
      - name: Build deployment package
        run: |
          cd frontend
          zip -r ../deploy.zip . -x '*.git*'
  
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-react
          environment_name: Dockerreact-env
          existing_bucket_name: 
          region: 
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          use_existing_version_if_available: true
        env:
          DEBUG: true
