name: Deploy Frontend
on:
  push:
    branches:
      - main
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Build and tag Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: false
          tags: inktense/docker-mock:${{ github.sha }}
  
      - name: Build deployment package
        run: |
          zip -r deploy.zip . -x '*.git*'
  
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-react
          environment_name: Dockerreact-env
          region: eu-west-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
